apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    env  : test
    owner: Alex
spec:
  type: ClusterIP
  selector:
    project: {{ .Release.Name }}-nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
